import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navig } from "./components/navig";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by Admin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* To see Header in every page */}
        <header>
          <p className="text-center bg-gray-800 text-white p-3.5">Hello Everyone, Welcome the the Next JS Tutorial </p>
        </header>
        <Navig />
        {children}
      </body>
    </html>
  );
}
